### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by baukeplugge** [motze92/office365-mail#10]
Hi Team,

i'm running Centos 8 with PHP 8.0.1 (cli) (built: Jan  5 2021 13:54:54) ( NTS gcc x86_64 )
Composer version 2.0.8 2020-12-03 17:20:38

When I want to install your module I get the message my PHP version is not supported.

```
[InvalidArgumentException]
  Package motze92/office365-mail has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

is it possible to support php version 8.01 ?

kind regards
Bauke

**Comment by motze92** [comment]
With release 2.0.5 we added PHP 8 support. 

https://github.com/motze92/office365-mail/releases/tag/2.0.5
