### ISSUE TITLE
Couldnt send email.

### ISSUE THREAD

**Issue by sharanvelu** [motze92/office365-mail#11]
This is the error i get through mail.
The actual issue is the package/queue returned success. 
But a mail from the sender address(me) to my inbox had this error message.

Remote Server returned '550 5.7.708 Service unavailable. Access denied, traffic not accepted from this IP. For more information please go to http://go.microsoft.com/fwlink/?LinkId=526653 AS(7230) [BM1PR01MB1076.INDPRD01.PROD.OUTLOOK.COM]'

**Comment by motze92** [comment]
Hi,

it seems more a problem with your Outlook mailbox.

Did you tried to send a mail from Outlook Web App?
