### ISSUE TITLE
Unsupported mail transport [office365mail]

### ISSUE THREAD

**Issue by sumit-tiwari-19** [motze92/office365-mail#12]
hi I am trying to use your Ms-Graph one. 
I have followed all the steps suggested.
But getting the error: ERROR: Unsupported mail transport [office365mail]. {"exception":"[object] (InvalidArgumentException(code: 0): Unsupported mail transport [office365mail]. at D:\laragon\www test\vendor\laravel\framework\src\Illuminate\Mail\MailManager.php:172)

**Comment by motze92** [comment]
Hi, did you added 
`'office365mail' => [
            'transport' => 'office365mail',
      ],
`
to mailers array in config/mail.php ?

**Comment by sumit-tiwari-19** [comment]
yes,
I have already added that as per the instructions mentioned.

**Comment by motze92** [comment]
which Laravel version do you use?

**Comment by sumit-tiwari-19** [comment]
Laravel Framework 8.32.1

**Comment by lewis-munyi** [comment]
In your `.env` file ensure it reads `MAIL_MAILER=office365mail` and not `MAIL_DRIVER=office365mail`. 
This could be the issue.

**Comment by lordisp** [comment]
I have the same issue: `Unsupported mail transport [office365mail]`.

```php
laravel/framework: 8.41
motze92/office365-mail: 1.0.7
```

```
MAIL_MAILER=office365mail
OFFICE365MAIL_CLIENT_ID=xxxx
OFFICE365MAIL_TENANT=xxxx
OFFICE365MAIL_CLIENT_SECRET=**** 
```

`config/mail.php`
```php
    'mailers' => [
        'office365mail' => [
            'transport' => 'office365mail',
        ],
```

**Comment by lordisp** [comment]
make sure you have the proper version installed:

```php
"motze92/office365-mail": "^2.0"
```
