### ISSUE TITLE
client secret expired date

### ISSUE THREAD

**Issue by anurat** [motze92/office365-mail#19]
I know this is not related directly to the package but the package relies on MS graph API
which can only allow to create a client secret with at most 24 months expired date.

I wonder whether this is just my organization settings and it can be configured to "never"
or this is the new policy that requires the client secret to always have expired date.

If it can be configured to "never" please let me know, otherwise workaround on the expired date 
would be appreciated.

**Comment by nikolai-belkin** [comment]
Looks like it is a maximum within MS Azure portal.

However, a work-around suggested [here](https://stackoverflow.com/questions/67075017/azure-app-registration-client-secrets-expiration) is to create a client secret token using a powershell script (I haven't tried it).

**Comment by motze92** [comment]
I have updated the instructions.
