### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by Martzy303** [motze92/office365-mail#21]
Have installed this on a new Laravel 9 and I get "Class "Illuminate\Mail\Transport\Transport" not found" on "\vendor\motze92\office365-mail\src\Transport\Office365MailTransport.php: 10"

**Comment by nikhilbhatia22** [comment]
Facing the same.

**Comment by nikhilbhatia22** [comment]
@Martzy303 Did you manage to solve it in any way?

**Comment by nikhilbhatia22** [comment]
This is because Laravel 9 has shifted from SwiftMailer to SymfonyMailer. @motze92 Any near-future plans of making it Laravel 9 compatible?

**Comment by motze92** [comment]
I am currently working on a Laravel 9 implementation. I will release it the next days.

**Comment by motze92** [comment]
https://github.com/motze92/office365-mail/releases/tag/3.0-beta Beta for Laravel 9 is now available. Large attachments are currently not working.

**Comment by Martzy303** [comment]
> 

No, I could not wait, so I just used microsoft/microsoft-graph, I needed just to send some simple emails, at least now I know how it works.

**Comment by regrub** [comment]
I moved from Laravel 8 to 9 and using the 3.0-beta I'm getting a "Client error: `POST https://graph.microsoft.com/v1.0/users/hello@example.com/sendmail` resulted in a `404 Not Found` response:" error.
I'm using the same mail entries in the .env and the same Azure app as in the L8 version.
Any suggestions?

**Comment by motze92** [comment]
Did you cleared all the caches?

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by regrub** [comment]
I did just now but no result. I don't know how the user hello@example.com gets there but is not one of mine. I use Guzzle 7.2

**Comment by regrub** [comment]
I just see al the stars in the emails... the mail is sent to user "hello at example dot com
<img width="1311" alt="Schermafbeelding 2022-05-13 om 13 34 11" src="https://user-images.githubusercontent.com/49644016/168275086-e452deac-2b1f-4729-aeec-f85d1c51de8b.png">
"

**Comment by Gor91** [comment]
Hi @regrub Do you solved this issue?

**Comment by regrub** [comment]
No, in fact I did not. I was hoping to spend some time investingating the problem, but I just took the code from version 8 to 9. So I presumed it would work. I kind of need it next week to work so tomorrow start working on it. Is there a new version coming to the beta?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Gor91 ***@***.***>
Verzonden: Thursday, August 25, 2022 9:02:23 AM
Aan: motze92/office365-mail ***@***.***>
CC: Rutger Burger ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [motze92/office365-mail] Laravel 9 (Issue #21)


Hi @regrub<https://github.com/regrub> Do you solved this issue?

**Comment by motze92** [comment]
It seems that you are using the wrong userprincipal name.
Can you try to go to https://developer.microsoft.com/de-de/graph/graph-explorer, Sign in with the account you are using to send the mail and do a request to https://graph.microsoft.com/v1.0/me ? In the response, you find the userprincipalname, which should be the from address.

**Comment by regrub** [comment]
Thank you for looking into this. I made a mistake and missed just that with the upgrade to Laravel 9.
It works like a dream now. Thanks!

Rutger

Van: motze92 ***@***.***>
Datum: donderdag, 25 augustus 2022 om 10:26
Aan: motze92/office365-mail ***@***.***>
CC: Rutger Burger ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [motze92/office365-mail] Laravel 9 (Issue #21)

It seems that you are using the wrong userprincipal name.
Can you try to go to https://developer.microsoft.com/de-de/graph/graph-explorer, Sign in with the account you are using to send the mail and do a https://graph.microsoft.com/v1.0/me request? In the response, you find the userprincipalname, which should be the from address.
