### ISSUE TITLE
Office 365 personal accounts

### ISSUE THREAD

**Issue by turbo124** [motze92/office365-mail#23]
Is it possible to use this package with o365 personal accounts? I am stuck with obtaining access tokens for personal accounts.

**Comment by motze92** [comment]
Theoretically yes, but then you have to create an authorization page. When you register your app, you can select what types of accounts you want to support.

Here a screenshot from app registration (in german):
![image](https://user-images.githubusercontent.com/41009610/163664548-1d64ca26-ab40-40c2-a474-3091138d1b1a.png)
