### ISSUE TITLE
AbstractTransport::$dispatcher must not be accessed before initialization

### ISSUE THREAD

**Issue by beard7** [motze92/office365-mail#31]
I'm using Laravel 9 with PHP 8.1 on Windows.

The regular smtp mailer is working fine, but switching to office365-mail v3.0 produces the error:
````
exception: "Error"
file: "C:\\Code\\insight-l9\\vendor\\symfony\\mailer\\Transport\\AbstractTransport.php"
line: 61
message: "Typed property Symfony\\Component\\Mailer\\Transport\\AbstractTransport::$dispatcher must not be accessed before initialization"
````
I've published the config file, edited the mail config and added appropriate entries to the .ENV file.

Any suggestions?

Thanks

**Comment by sagarWappzo** [comment]
Facing same issue. Please help to fix this issue.

Typed property Symfony\Component\Mailer\Transport\AbstractTransport::$dispatcher must not be accessed before initialization

**Comment by scoalaauto** [comment]
I am getting the same error after upgrading to Laravel 9 on Ubuntu

**Comment by bamfix** [comment]
manually adding the latest [commit ](https://github.com/motze92/office365-mail/commit/91891932679e423d9c884dc3240c20c994d9f108) from the unreleased [3.x branch](https://github.com/motze92/office365-mail/tree/3.x) fixed the issue for me.

> src/Transport/Office365MailTransport.php

```php
    public function __construct()
    {
        parent::__construct();
        //this is missing ^
    }
```

@motze92 did you forget to release your latest commit for the 3.0-beta?

**Comment by cinek1992** [comment]
@motze92 any chance to release new version with this fix?

**Comment by motze92** [comment]
New version created.
