### ISSUE TITLE
Sending large attachments is not possible with Laravel 9 / office365-mail v3.1-beta

### ISSUE THREAD

**Issue by J87NL** [motze92/office365-mail#33]
https://github.com/motze92/office365-mail/releases/tag/3.0-beta Beta for Laravel 9 is now available. Large attachments are currently not working.

_Originally posted by @motze92 in https://github.com/motze92/office365-mail/issues/21#issuecomment-1100260421_
            

We receive the following error with larger attachments in Laravel 9.50.2 and office365-mail v3.1-beta:

```
[2023-02-06 15:07:59] production.ERROR: Client error: `POST [https://graph.microsoft.com/v1.0/users/{email}/messages`](https://graph.microsoft.com/v1.0/users/{email}/messages) resulted in a `400 Bad Request` response:
{"error":{"code":"UnableToDeserializePostBody","message":"were unable to deserialize "}}
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST [https://graph.microsoft.com/v1.0/users/{email}/messages`](https://graph.microsoft.com/v1.0/users/{email}/messages) resulted in a `400 Bad Request` response.
```

We have the permission `Mail.ReadWrite` enabled. Is there maybe a workaround or fix available for this? Thanks in advance!

**Comment by J87NL** [comment]
@motze92 any update on this? Is there a way to make sending larger images working again in the 3.0-version?

**Comment by motze92** [comment]
Now its working: https://github.com/motze92/office365-mail/releases/tag/3.1.1
