### ISSUE TITLE
cc and bcc does not work

### ISSUE THREAD

**Issue by michaelnguyen547** [motze92/office365-mail#7]
all `cc` and `bcc` are grouped together in the `to` field, not in their appropriate `cc` or `bcc` fields

Sample code

```
Mail::to('a@gmail.com')
      ->cc('b@gmail.com')
      ->bcc('c@gmail.com')
      ->send(new SampleMail());
```

`a@gmail.com` , `b@gmail.com`, `c@gmail.com` are in `to` field. 

I expected `a@gmail.com` in `to` field, `b@gmail.com` in `cc` field, and `c@gmail.com` in `bcc` field

Update 1: test with `log` mail driver, I got correct `cc` and `bcc` fields set.

**Comment by motze92** [comment]
Fixed with release https://github.com/motze92/office365-mail/releases/tag/2.0.1
